ALTER TABLE reconciliations
    ADD COLUMN IF NOT EXISTS chi_square DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS critical_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS statistical_validity BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS confidence_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS outlier_index BIGINT NOT NULL DEFAULT -1,
    ADD COLUMN IF NOT EXISTS outlier_tag TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS outlier_contribution DOUBLE PRECISION NOT NULL DEFAULT 0;
